name: CI

on:
  push:
    paths:
      - '**.hpp'
      - '**.cc'
  pull_request:
    paths:
      - '**.hpp'
      - '**.cc'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: textbook/git-checkout-submodule-action@2.1.1

      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 11

      - run:
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11

      - run:
          sudo apt install libtbb-dev

      - uses: actions/setup-python@v4.3.1

      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          setup-options: -Db_coverage=true
          options: --verbose

      - run: |
          sudo apt install lcov
          mkdir coverage
          lcov -c -d . -o coverage/lcov.info
          lcov -r coverage/lcov.info "/usr*" "*test/lib/ut*" -o coverage/lcov.info

      - uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: ZedThree/clang-tidy-review@v0.10.1
        if: github.event_name == 'pull_request'
        with:
          build_dir: 'build'
          clang_tidy_version: 14
          config_file: '.clang-tidy'
          exclude: 'lib'

      - uses: jidicula/clang-format-action@v4.9.0
        if: github.event_name == 'pull_request'
        with:
          clang-format-version: 15
          exclude-regex: 'lib'
